-- MySQL Script generated by MySQL Workbench
-- Thu Apr  4 13:56:27 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ticketoppdrag
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ticketoppdrag
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ticketoppdrag` DEFAULT CHARACTER SET utf8 ;
USE `ticketoppdrag` ;

-- -----------------------------------------------------
-- Table `ticketoppdrag`.`Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticketoppdrag`.`Category` (
  `idCat` INT NOT NULL,
  `typeCat` VARCHAR(45) NULL,
  PRIMARY KEY (`idCat`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticketoppdrag`.`statcat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticketoppdrag`.`statcat` (
  `idStat` INT NOT NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`idStat`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticketoppdrag`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticketoppdrag`.`users` (
  `idusers` INT GENERATED ALWAYS AS () VIRTUAL,
  `brukernavn` VARCHAR(45) NOT NULL,
  `passord` VARCHAR(45) NOT NULL,
  `admin` INT NOT NULL,
  PRIMARY KEY (`idusers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticketoppdrag`.`henvendelsesr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticketoppdrag`.`henvendelsesr` (
  `idhenvendelsesr` INT NOT NULL,
  `henven` VARCHAR(255) NULL,
  `userid` INT NULL,
  `status` INT NULL,
  `cat` INT NULL,
  `date` DATETIME NULL,
  PRIMARY KEY (`idhenvendelsesr`),
  INDEX `fk_henvendelsesr_Category_idx` (`cat` ASC),
  INDEX `fk_henvendelsesr_statcat1_idx` (`status` ASC),
  INDEX `fk_henvendelsesr_users1_idx` (`userid` ASC),
  CONSTRAINT `fk_henvendelsesr_Category`
    FOREIGN KEY (`cat`)
    REFERENCES `ticketoppdrag`.`Category` (`idCat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_henvendelsesr_statcat1`
    FOREIGN KEY (`status`)
    REFERENCES `ticketoppdrag`.`statcat` (`idStat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_henvendelsesr_users1`
    FOREIGN KEY (`userid`)
    REFERENCES `ticketoppdrag`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
